# Generated by Django 3.2.13 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nabclockd", "0004_config_sleep_wakeup_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="stay_awake",
            field=models.BooleanField(default=False),
        ),
    ]
