# Generated by Django 3.2.13 on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nabd", "0002_alter_config_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="quiet_mode",
            field=models.BooleanField(default=False),
        ),
    ]
